[Actions] Updated .github/actions/database-deploy/action.yml

diff --git a/.github/actions/database-deploy/action.yml b/.github/actions/database-deploy/action.yml
--- a/.github/actions/database-deploy/action.yml
+++ b/.github/actions/database-deploy/action.yml
@@ -33,7 +33,7 @@ runs:
         echo "Looking for dacpac"
         DACPAC="$(find "${{github.workspace}}/src" -type f -iname "*.dacpac" | head -1)"
         echo "Found: $DACPAC"
-        [ -z "$DACPAC" ]; && echo "Error: DACPAC not found!" && exit 1
+        [ -z "$DACPAC" ] && echo "Error: DACPAC not found!" && exit 1
         echo "DACPAC=$DACPAC" >> "$GITHUB_OUTPUT"
 
     - name: "Install SQLPackage tool"
